# Project Name
TARGET = Drum
# TARGET = Dumb

# Sources
CPP_SOURCES = Drum.cpp
# CPP_SOURCES = Dumb.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

