# Project Name
# TARGET = SimpleOscillator
TARGET = DuoOscillator

# Sources
# CPP_SOURCES = SimpleOscillator.cpp
CPP_SOURCES = DuoOscillator.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

