# Project Name
TARGET = midi_triggers_osc

# Sources
# CPP_SOURCES = midi_triggers_osc.cpp
CPP_SOURCES = midi.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
